FROM python:3.11-alpine as base

ARG DEV=false
ENV PYTHONUNBUFFERED=1 \
  PYTHONDONTWRITEBYTECODE=1 \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100

# Install system dependencies
RUN apk update && \
  apk add --no-cache \
  libpq \
  gcc \
  musl-dev \
  python3-dev \
  libffi-dev \
  openssl-dev

# Set container working directory
WORKDIR /app

# Copy requirements files
COPY requirements.txt ./

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the application
COPY . .

# Expose debugging port
EXPOSE 5678

# Expose application port
EXPOSE 8000

# Run the application with hot reloading
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]