services:
  api:
    container_name: mindsherpa_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5678:5678"
      - "8002:8000"
    volumes:
      - .:/app
      - /app/__pycache__/
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    # command:
    #   [
    #     "sh",
    #     "-c",
    #     "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload -Xfrozen_modules=off",
    #   ]
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: mindsherpa_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
