services:
  api:
    container_name: mindsherpa-api
    build:
      context: .
      dockerfile: Dockerfile.dev
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: pyproject.toml
    ports:
      - "5678:5678"
      - "8002:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - SUPABASE_URL
      - SUPABASE_KEY
      - GROQ_API_KEY
      - OPENAI_API_KEY
      - CHROMA_SERVER_AUTHN_CREDENTIALS
      - CHROMA_SERVER_AUTHN_PROVIDER
    command: uv run uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
      - chroma

  postgres:
    image: postgres:latest
    container_name: mindsherpa-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  chroma:
    container_name: mindsherpa-chroma
    image: ghcr.io/chroma-core/chroma:0.5.6.dev97
    environment:
      CHROMA_SERVER_AUTHN_CREDENTIALS: "test-token"
      CHROMA_SERVER_AUTHN_PROVIDER: "chromadb.auth.token_authn.TokenAuthenticationServerProvider"
      CHROMA_AUTH_TOKEN_TRANSPORT_HEADER: "X-Chroma-Token"
    volumes:
      - chroma_data:/chroma/chroma
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
  chroma_data:
