[project]
name = "mindsherpa-api"
version = "0.1.0"
description = "An API that enables clients to interact with the Mindsherpa platform."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.113.0",
    "langchain>=0.2.16",
    "langchain-community>=0.2.16",
    "langchain-openai>=0.1.23",
    "openai>=1.43.1",
    "python-dotenv>=1.0.1",
    "uvicorn>=0.30.6",
    "strawberry-graphql[fastapi]>=0.239.2",
    "pytest>=8.3.2",
    "sqlalchemy>=2.0.34",
    "psycopg2-binary>=2.9.9",
    "pydantic-settings>=2.4.0",
    "pyjwt>=2.9.0",
    "groq>=0.11.0",
    "langchain-groq>=0.1.9",
    "supabase>=2.7.4",
    "alembic>=1.13.2",
    "pre-commit>=3.8.0",
    "langgraph>=0.2.19",
    "chromadb>=0.5.5",
    "langchain-chroma>=0.1.2",
    "apscheduler>=3.10.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/main"]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 110
target-version = "py310"
extend-exclude = ["/usr/lib/*"]

[tool.ruff.lint]
ignore = [
    "E501", # line too long - will be fixed in format
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false
docstring-code-format = true
exclude = [
    "src/flux/_version.py", # generated by setuptools_scm
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true
known-local-folder = ["src"]
known-first-party = ["flux"]

[tool.uv]
dev-dependencies = ["ruff>=0.6.2", "fastapi-cli>=0.0.5"]
