"""Add in_vector_store to Focus

Revision ID: 3f5fc0a85ceb
Revises: 24f51172a854
Create Date: 2024-09-12 22:04:56.298865

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f5fc0a85ceb"
down_revision: Union[str, None] = "24f51172a854"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "focus",
        sa.Column("in_vector_store", sa.Boolean(), nullable=False, default=False, server_default=sa.false()),
    )
    op.alter_column("profiles", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("profiles", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("profiles", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("profiles", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.drop_column("focus", "in_vector_store")
    # ### end Alembic commands ###
