"""upgrade

Revision ID: 6c4194beb4b8
Revises: 6e0f2ab4072b
Create Date: 2024-08-30 07:32:38.482628

"""

from re import T
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c4194beb4b8"
down_revision: Union[str, None] = "6e0f2ab4072b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_actions_id"), "actions", ["id"], unique=True)
    op.create_index(op.f("ix_chats_id"), "chats", ["id"], unique=True)
    op.create_index(op.f("ix_context_id"), "context", ["id"], unique=True)
    op.create_index(op.f("ix_entities_id"), "entities", ["id"], unique=True)
    op.create_index(op.f("ix_entity_memories_id"), "entity_memories", ["id"], unique=True)
    op.create_index(op.f("ix_memories_id"), "memories", ["id"], unique=True)
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=True)
    op.create_index(op.f("ix_notes_id"), "notes", ["id"], unique=True)
    op.create_index(op.f("ix_profiles_id"), "profiles", ["id"], unique=True)
    op.create_index(op.f("ix_queues_id"), "queues", ["id"], unique=True)
    op.add_column("refresh_tokens", sa.Column("expires_at", sa.DateTime(), nullable=False))
    op.create_index(op.f("ix_refresh_tokens_id"), "refresh_tokens", ["id"], unique=True)
    op.create_index(op.f("ix_relationships_id"), "relationships", ["id"], unique=True)
    op.create_index(op.f("ix_system_state_id"), "system_state", ["id"], unique=True)
    op.create_index(op.f("ix_tags_id"), "tags", ["id"], unique=True)
    op.add_column("users", sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"))
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_column("users", "is_active")
    op.drop_index(op.f("ix_tags_id"), table_name="tags")
    op.drop_index(op.f("ix_system_state_id"), table_name="system_state")
    op.drop_index(op.f("ix_relationships_id"), table_name="relationships")
    op.drop_index(op.f("ix_refresh_tokens_id"), table_name="refresh_tokens")
    op.drop_column("refresh_tokens", "expires_at")
    op.drop_index(op.f("ix_queues_id"), table_name="queues")
    op.drop_index(op.f("ix_profiles_id"), table_name="profiles")
    op.drop_index(op.f("ix_notes_id"), table_name="notes")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index(op.f("ix_memories_id"), table_name="memories")
    op.drop_index(op.f("ix_entity_memories_id"), table_name="entity_memories")
    op.drop_index(op.f("ix_entities_id"), table_name="entities")
    op.drop_index(op.f("ix_context_id"), table_name="context")
    op.drop_index(op.f("ix_chats_id"), table_name="chats")
    op.drop_index(op.f("ix_actions_id"), table_name="actions")
    # ### end Alembic commands ###
