"""add profile fields to user

Revision ID: 24f51172a854
Revises: 6c4194beb4b8
Create Date: 2024-09-02 20:23:26.177063

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24f51172a854"
down_revision: Union[str, None] = "6c4194beb4b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("provider", sa.String(), nullable=False, server_default="apple"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "provider")
    # ### end Alembic commands ###
