"""add focus_ids to message

Revision ID: cf88c5a65698
Revises: 3f5fc0a85ceb
Create Date: 2024-09-24 20:33:29.996287

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cf88c5a65698"
down_revision: Union[str, None] = "3f5fc0a85ceb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("focus_ids", sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "focus_ids")
    # ### end Alembic commands ###
