"""add focus table

Revision ID: 31656ae66c49
Revises: e75809b95dc7
Create Date: 2024-08-08 18:01:29.294367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31656ae66c49'
down_revision: Union[str, None] = 'e75809b95dc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('task_size', sa.String(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('focus')
    # ### end Alembic commands ###
