"""Initial migration

Revision ID: 4f4580079301
Revises: 
Create Date: 2024-08-04 23:31:21.059320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f4580079301'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('attributes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queues',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_state',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('current_focus', sa.String(), nullable=True),
    sa.Column('mood', sa.String(), nullable=True),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('queue_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['queue_id'], ['queues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_memories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('memory_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_tags',
    sa.Column('memory_id', sa.String(), nullable=True),
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_table('relationships',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity1_id', sa.String(), nullable=True),
    sa.Column('entity2_id', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['entity1_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['entity2_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('memory_tags')
    op.drop_table('entity_memories')
    op.drop_table('actions')
    op.drop_table('tags')
    op.drop_table('system_state')
    op.drop_table('queues')
    op.drop_table('memories')
    op.drop_table('entities')
    op.drop_table('context')
    # ### end Alembic commands ###
