"""align models with gql schema

Revision ID: 6674e2e67df2
Revises: fb8c8d46203a
Create Date: 2024-08-05 01:17:37.713501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6674e2e67df2'
down_revision: Union[str, None] = 'fb8c8d46203a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_tags',
    sa.Column('note_id', sa.String(), nullable=True),
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.add_column('chats', sa.Column('title', sa.String(), nullable=False))
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('chats', 'title')
    op.drop_table('note_tags')
    # ### end Alembic commands ###
