"""remove focus.status

Revision ID: e790245feccb
Revises: a9f792c82daa
Create Date: 2024-08-20 15:50:20.772956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e790245feccb'
down_revision: Union[str, None] = 'a9f792c82daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('focus', 'status')
    op.alter_column('messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('notes', 'profile_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notes', 'profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('messages', 'profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('messages', 'message',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('focus', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chats', 'profile_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
