"""relationships

Revision ID: fb8c8d46203a
Revises: e4d6f72d4b9b
Create Date: 2024-08-05 00:03:10.417625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8c8d46203a'
down_revision: Union[str, None] = 'e4d6f72d4b9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('profile_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'actions', 'profiles', ['profile_id'], ['id'])
    op.add_column('context', sa.Column('profile_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'context', 'profiles', ['profile_id'], ['id'])
    op.add_column('entities', sa.Column('profile_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'entities', 'profiles', ['profile_id'], ['id'])
    op.add_column('memories', sa.Column('profile_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'memories', 'profiles', ['profile_id'], ['id'])
    op.add_column('queues', sa.Column('profile_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'queues', 'profiles', ['profile_id'], ['id'])
    op.add_column('system_state', sa.Column('profile_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'system_state', 'profiles', ['profile_id'], ['id'])
    op.add_column('tags', sa.Column('profile_id', sa.String(), nullable=True))
    op.add_column('tags', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'tags', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'created_at')
    op.drop_column('tags', 'profile_id')
    op.drop_constraint(None, 'system_state', type_='foreignkey')
    op.drop_column('system_state', 'profile_id')
    op.drop_constraint(None, 'queues', type_='foreignkey')
    op.drop_column('queues', 'profile_id')
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_column('memories', 'profile_id')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_column('entities', 'profile_id')
    op.drop_constraint(None, 'context', type_='foreignkey')
    op.drop_column('context', 'profile_id')
    op.drop_constraint(None, 'actions', type_='foreignkey')
    op.drop_column('actions', 'profile_id')
    # ### end Alembic commands ###
