name: Run Tests

on:
  pull_request:
    branches: [main] # Adjust this if your main branch has a different name

env:
  ENVIRONMENT: test
  CHROMA_HOST: localhost
  CHROMA_PORT: 8000
  JWT_SECRET: fake_jwt_secret
  GROQ_API_KEY: fake_groq_api_key
  OPENAI_API_KEY: fake_openai_api_key
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0Z2R2cW10YmJ0aWZ2Z2N0Z3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTYzMjI4MjQsImV4cCI6MjAxMTg5ODgyNH0.i9QWzUY21Y4q0sZ57YB5489J7x089g64vj9229111"
  SUPABASE_URL: "http://supabase:3000"
  DATABASE_URL: postgresql://postgres:postgres@localhost:5434/test_db

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5434:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file
          pip install alembic pytest

      - name: Run database migrations
        run: alembic upgrade head

      - name: Run tests
        run: pytest tests/ -v
